### PR TITLE
This should fix all issues and add many new features

### PR DESCRIPTION
**Pull request by jake-cryptic**
Many new features include better link handling, password changing, improved uploader, fixed deletions, many many bugs squashed and more!

### CODE REVIEW

**Comment by smartclash** [comment]
@jake-cryptic Hey, can you please check my website? I think somebody hacked it! I think they are executing scripts from the uploads section!

**Comment by smartclash** [comment]
@jake-cryptic Okay, found the bloody hacker. He uploaded script on the patch folder. I have now disabled php execution over there by adding `RemoveHandler .php .phtml .php3
RemoveType .php .phtml .php3
php_flag engine off` on the `.htaccess` file

**Comment by jake-cryptic** [comment]
Yes, I had that in the htaccess file and was wondering why I couldn't see that file in your server

**Comment by smartclash** [comment]
@jake-cryptic No use, that berkan is still hacking my server. Please look at that flaw!

**Comment by jake-cryptic** [comment]
Don't login to smartpatch, I think someone altered the login and create scripts, if i was you I would wipe the files and download the github version of it and use that

**Comment by jake-cryptic** [comment]
Karan, he ran something called c99 shell which is a PHP hacking script, I reccomend you disconnect that computer from the internet because it's probably not a problem with the website, but the OS

**Comment by smartclash** [comment]
@jake-cryptic Yup, he did use c99. I did stop execution in patch folder and i did disconnect that from the computer. And can you please elaborate what do you mean by  ***I recommend you disconnect that computer from the internet because it's probably not a problem with the website, but the OS***

**Comment by jake-cryptic** [comment]
Shells are semi-root, so he has done something to your computer, you should disconnect it from the internet to stop his access and figure out what he has done to your server, was it Berkan or someone else?

**Comment by smartclash** [comment]
@jake-cryptic Well. I have hosted it in a web hosting site. I will stop access to smart patch and i will figure it out

**Comment by jake-cryptic** [comment]
Is it a VPS you use?

**Comment by smartclash** [comment]
@jake-cryptic Good, i've found the issue. He had already backed up the c99 shell in every directory. I have deleted it. May i know does your latest version 3.2 checks what's inside the patch zip file before uploading? I am now using your latest version. Planning to change the design of the latest one after wards.

**Comment by jake-cryptic** [comment]
Yes, the latest version checks that only sc, csv and JSON files are being uploaded

**Comment by jake-cryptic** [comment]
I will implement much better security in the next version, which will check if files have been edited etc, I'm already thinking of new security techniques

**Pull request merged**
